import axios from 'axios';

const api = axios.create({
  baseURL: process.env.REACT_APP_API_URL || 'eyJraWQiOiJaTUtjVXciLCJhbGciOiJFUzI1NiJ9.eyJleHAiOjI1NjMyOTM1NDAsImlhdCI6MTc3NDg5MzU0MCwibmJmIjoxNzc0ODkzNTQwLCJzdWIiOiJ7XCJ0b2tlblJlZklkXCI6XCJiMDJkYjY3Ny1mOGJkLTQ5MmQtYTkxZC1iYTZmZTJmN2UwNzZcIixcInZlbmRvckludGVncmF0aW9uS2V5XCI6XCJlMzFmZjIzYjA4NmI0MDZjODg3NGIyZjZkODQ5NTMxM1wiLFwidXNlckFjY291bnRJZFwiOlwiOTI2ODVlNzUtYmY3My00Y2VkLWJmMWMtZDI5ZmE1NTVhMWI5XCIsXCJkZXZpY2VJZFwiOlwiZDdiYmVmYWItMmNhNC01MTA0LWE1ZDItMTlkY2U2NWM3MGE5XCIsXCJzZXNzaW9uSWRcIjpcImZiZjY1OGM1LWJhNWEtNGNhOC1iYjMxLWM5M2U5ODg0NjNmMFwiLFwiYWRkaXRpb25hbERhdGFcIjpcIno1NC9NZzltdjE2WXdmb0gvS0EwYkZrT3VYNUE1NU1EZTlEM3MvRitVM0pSTkczdTlLa2pWZDNoWjU1ZStNZERhWXBOVi9UOUxIRmtQejFFQisybTdRPT1cIixcInJvbGVcIjpcImF1dGgtdG90cFwiLFwic291cmNlSXBBZGRyZXNzXCI6XCIyNDA5OjQwYzI6NjQzZDpiMDQ1OjQ5OGM6NmY2NDo5YWU6ZDlmMSwxNzIuNzEuMTk4Ljk1LDM1LjI0MS4yMy4xMjNcIixcInR3b0ZhRXhwaXJ5VHNcIjoyNTYzMjkzNTQwNzQ1LFwidmVuZG9yTmFtZVwiOlwiZ3Jvd3dBcGlcIn0iLCJpc3MiOiJhcGV4LWF1dGgtcHJvZC1hcHAifQ.qoKekWlBTyO6WduyXz7cQWVZyPKXviv8Lbyv7eU348W_u1pnWACeQ6AsOq0ySHJ3i0uNrxoohSMYf9-FAFbN0g',
});

// Attach JWT to every request automatically
api.interceptors.request.use(config => {
  const token = localStorage.getItem('token');
  if (token) config.headers.Authorization = `Bearer ${token}`;
  return config;
});

export default api;
